# nixpacks.toml - Railway deployment configuration

[phases.setup]
# This line tells Railway to use Python 3.11
nixPkgs = ["...", "python311"]

[phases.install]
# This tells Nixpacks to install your Python packages
cmds = ["pip install -r requirements.txt"]

[phases.build]
# This tells Nixpacks to run your database migrations
cmds = ["alembic upgrade head"]

[start]
# This tells Nixpacks how to start your web server
command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"