"""Add met_value to exercises and calories_burned to logs

Revision ID: 6afb06aff5d4
Revises: 47c18ca4dea5
Create Date: 2025-10-07 19:08:34.372078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afb06aff5d4'
down_revision = '47c18ca4dea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('met_value', sa.Float(), nullable=True))
    op.add_column('workout_logs', sa.Column('calories_burned', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'calories_burned')
    op.drop_column('exercises', 'met_value')
    # ### end Alembic commands ###