"""raname category to exercise_type in Exercise model

Revision ID: 8821bd55a06e
Revises: d8f7bfbde23c
Create Date: 2025-10-10 20:24:08.767981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8821bd55a06e'
down_revision = 'd8f7bfbde23c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_type', sa.String(), nullable=False))
    op.drop_column('exercises', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'exercise_type')
    # ### end Alembic commands ###