"""remove gooogle_place and added gym code

Revision ID: a4d3c81bbd20
Revises: bd532898e575
Create Date: 2025-10-23 10:32:56.088282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d3c81bbd20'
down_revision = 'bd532898e575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('gym_code', sa.String(), nullable=True))
    op.drop_index('ix_gyms_google_place_id', table_name='gyms')
    op.create_index(op.f('ix_gyms_gym_code'), 'gyms', ['gym_code'], unique=True)
    op.drop_column('gyms', 'google_place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('google_place_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gyms_gym_code'), table_name='gyms')
    op.create_index('ix_gyms_google_place_id', 'gyms', ['google_place_id'], unique=False)
    op.drop_column('gyms', 'gym_code')
    # ### end Alembic commands ###