"""Add preferences column to user model

Revision ID: d01dbb869286
Revises: 4a49da61342d
Create Date: 2025-10-22 14:53:37.269179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd01dbb869286'
down_revision = '4a49da61342d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_tips', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_tips', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('exercise_tips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_videos', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_videos', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('exercise_videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'muscle_groups',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gym_bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gyms', 'operating_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gyms', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gyms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('meal_plans', 'meals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('meal_plans', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('meal_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('oauth_account_user_id_fkey', 'oauth_account', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_account', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.alter_column('tip_interactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tip_interactions', 'tip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tip_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('users', 'dietary_restrictions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_preferences', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('video_preferences', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workout_logs', 'exercises_completed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('workout_logs', 'workout_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workout_plans', 'exercises',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('workout_plans', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_plans', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_plans', 'exercises',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('workout_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workout_logs', 'workout_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_logs', 'exercises_completed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('workout_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('video_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_preferences', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video_preferences', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'dietary_restrictions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('users', 'preferences')
    op.alter_column('tip_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tip_interactions', 'tip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tip_interactions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'oauth_account', type_='foreignkey')
    op.create_foreign_key('oauth_account_user_id_fkey', 'oauth_account', 'users', ['user_id'], ['id'])
    op.alter_column('meal_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_plans', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('meal_plans', 'meals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('meal_plans', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('gyms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gyms', 'max_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gyms', 'operating_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('gym_bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'muscle_groups',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('exercise_videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_videos', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exercise_videos', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise_tips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_tips', 'popularity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exercise_tips', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###