"""Add onboarding flag to user

Revision ID: d8f7bfbde23c
Revises: 6afb06aff5d4
Create Date: 2025-10-09 09:33:10.253319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f7bfbde23c'
down_revision = '6afb06aff5d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_onboarding')
    # ### end Alembic commands ###