"""Add gyms, gym_bookings, and user gym fields

Revision ID: gym_booking_additions
Revises: 
Create Date: 2025-10-21 18:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'gym_booking_additions'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###

    # Create gyms table
    op.create_table(
        'gyms',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, nullable=False, index=True),
        sa.Column('address', sa.String, nullable=False),
        sa.Column('city', sa.String, nullable=True, index=True),
        sa.Column('state', sa.String, nullable=True),
        sa.Column('country', sa.String, nullable=True),
        sa.Column('latitude', sa.Float, nullable=True),
        sa.Column('longitude', sa.Float, nullable=True),
        sa.Column('logo_url', sa.String, nullable=True),
        sa.Column('operating_hours', sa.JSON, nullable=True, default=dict),
        sa.Column('max_capacity', sa.Integer, default=100),
        sa.Column('google_place_id', sa.String, nullable=True, unique=True, index=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    )

    # Create gym_bookings table
    op.create_table(
        'gym_bookings',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('gym_id', sa.Integer, sa.ForeignKey('gyms.id'), nullable=False),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, index=True),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String, nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    )

    # Add gym_id column to users table
    op.add_column('users', sa.Column('gym_id', sa.Integer, sa.ForeignKey('gyms.id'), nullable=True, index=True))
    # Add last_gym_change column to users table
    op.add_column('users', sa.Column('last_gym_change', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands


def downgrade():
    # ### commands auto generated by Alembic ###

    op.drop_column('users', 'last_gym_change')
    op.drop_column('users', 'gym_id')
    op.drop_table('gym_bookings')
    op.drop_table('gyms')

    # ### end Alembic commands
